### PR TITLE
Select first record or create a new one if there is no match

### PR DESCRIPTION
**Pull request by sestrella**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by Vlix** [comment]
This will throw an error when the to be inserted record can't be inserted because of a uniqueness constraint, for example. Is that the intended functionality?

**Comment by sestrella** [comment]
@Vlix sorry for the late reply, perhaps bringing up the use case I had in mind might help here. So far I was thinking about using this function in scenarios like seed data, where the model looks like follows:

```hs
share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
Role
  name        Text -- assuming there is a unique constraint on this column
  description Text
|]

findOrCreateRole Role{..}@role =  selectFirstOrInsert [RoleName ==. roleName] role
```

However, after a second thought, I completely agree with you this operation could fail, in which case perhaps it would make more sense to replace `[Filter record]` with `Unique record` in order to make more explicit there is a unique constraint:

```hs
getUniqueOrInsert
  :: (OnlyOneUniqueKey record, ...)
  => record
  -> ReaderT backend m (Entity record)
getUniqueOrInsert rec = getUniqueByOrInsert (onlyUniqueP rec) rec

getUniqueByOrInsert
  :: (..)
  => Unique record 
  -> record
  -> ReaderT backend m (Entity record)
getUniqueByOrInsert unique record = do
  mrecord <- getBy unique
  case mrecord of
    Nothing   -> insertEntity record
    (Just rec) -> return rec
```

What do you think?

**Comment by Vlix** [comment]
Honestly, it sounds like you just want to use `insertBy`, which takes a record and returns `Either (Entity record) (Key record)`.
Using the record you inserted after the `Right` case is returned would be identical to what you're suggesting, and I don't really see why that would need to be a new function in the library...

```haskell
myFunc rec = insertBy rec >>= return . either id (const rec)
```

**Comment by parsonsmatt** [comment]
A problem here is that the unique records may not be the same in the non-unique fields. And a problem with the suggested PR is that there's no guarantee that the `entity` you insert satisfies the conditions you provided.

I'm generally inclined to include helpers and convenience functions into the library if the obvious implementation isn't right or fast for some reason. `maybe (insertEntity entity) pure =<< getBy unique` is very short, and I can't see why it wouldn't be right.

**Comment by sestrella** [comment]
@Vlix, @parsonsmatt fair enough, I appreciate all the feedback, for now, I would go with the short hard function @Vlix suggested.

**Pull request closed without merging**
