### PR TITLE
Documentation Fields on EntityDef and FieldDef

### LINKED ISSUE #864: Feature request: Documentation in Entity Syntax
I'd like to be able to write:

```
-- models/schema

-- | The User type is the thing of the bar
User
  -- | The user name is how we refer to users
  name String

-- | Dogs are so good I love to pet dogs
Dog
  -- | Dogs have one true owner
  owner UserId
```

And have those documentation fields be available in the `EntityDef` and `FieldDef` records. They could be used to:

a) generate Haddock documentation for the generated Haskell types
b) generate [Postgresql `COMMENT`s](https://www.postgresql.org/docs/10/sql-comment.html)
c) Markdown or similar schema documentation from the `[EntityDef]` list

The parser already recognizes `--` as a comment. In keeping with Haskell's syntax, I make three proposals:

1. We reuse `-- |` and `-- ^` to indicate that the commented text is a documentation comment, just like Haddock.
2. We only use `-- |` to simplify parsing logic and the overall grammar.
3. We use a new delimiter or comment syntax.

### PR DESCRIPTION
**Pull request by parsonsmatt**
This PR adds documentation fields to entities, opening the door for the QuasiQuoter to add them in later.

---

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
@psibi @MaxGabriel How would y'all feel about getting this merged now, and allowing documentation extensions to come later? We've got an internal library for documenting `persistent` entities in a separate EDSL, and it would really simplify a lot of that library's logic for the documentation comments to exist on the `EntityDef` types themselves.

**Comment by MaxGabriel** [comment]
That sounds alright to me. Seems like a natural progression. There should
probably be a comment saying that the parser support isn’t added yet though

**Comment by psibi** [comment]
LGTM. Are you planning to work on the parser support also ?

**Comment by parsonsmatt** [comment]
Yeah, I'm going to implement the parsing side of things. I've got an internal library at work for adding this documentation after-the-fact in Haskell which I'm going to open-source first.

**Pull request merged**
