### PR TITLE
Add fieldError to export list

### PR DESCRIPTION
**Pull request by brandon-leapyear**
Allows people implementing `PersistEntity` manually to use the `fieldError` helper

Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Try merging master - there's an upper bound in place to prevent the cabal solver from picking that version.

**Comment by brandon-leapyear** [comment]
What version bound are you referring to?

**Comment by parsonsmatt** [comment]
`persistent-mongoDB` needs a `< 2.6` constraint on `mongoDB` package. It's in master, and I was able to get it working by just restarting the CI against master.

**Comment by brandon-leapyear** [comment]
This PR is not about persistwn-mongodb?

**Comment by parsonsmatt** [comment]
I know. We didn't have an upper bound on `persistent-mongoDB` so the cabal builders were failing because they were getting the newest version which was incompatible. That's been fixed. So all we need to get this merged is the checkboxes to be done :smile:

**Comment by brandon-leapyear** [comment]
ah ok. I was confused because it looks like CI is passing on this branch.

I wasn't sure which of the checkboxes you needed me to fix. Does this change really require a version bump?

**Comment by parsonsmatt** [comment]
The changelog needs to be updated. If you don't want this released, then you can put it in an `Unreleased` section instead of a minor version bump. If you do want it to be released soon, then we do need to have a new version number to publish it on Hackage.

A `@since` annotation on the function denoting the version it was released would also be good.

**Comment by brandon-leapyear** [comment]
I wasn't sure what version to put in `@since` because I'm not setting a next version, so I put `@since 2.8.1` for now. Let me know if that needs to be changed

**Comment by parsonsmatt** [comment]
Released in `persistent-template-2.8.2`, thanks so much! :smile:

**Pull request merged**
