### PR TITLE
A fix for #1117, I think

### PR DESCRIPTION
**Pull request by NorfairKing**
Before submitting your PR, check that you've:

- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by NorfairKing** [comment]
@parsonsmatt Is this what you mind? I wanted to add a golden test but could not find where the golden tests are defined.

**Comment by parsonsmatt** [comment]
We don't really have golden tests, but you could write a test for the `fromPersistValue` that verifies it parses the values that were failing before.

```haskell
describe "fromPersistValue" $ 
  describe "UTCTime" $ 
    it "works with format" $ 
     fromPersistValue (PersistText "problematic example here")
      `shouldBe` Right parsedTime
```

**Comment by NorfairKing** [comment]
@parsonsmatt I'm happy to do that either here or in a next PR, but where should I put that test then?

**Comment by parsonsmatt** [comment]
Since it's pure, it can go in `persistent/test/Main.hs`

**Comment by NorfairKing** [comment]
Done, make sure to squash the commits.

**Comment by parsonsmatt** [comment]
awesome, thanks! Code looks great. Please remember to update the relavant Changelog and put a link to this in, it should be going in with 2.11 :)

**Comment by NorfairKing** [comment]
Also done. Anything else? :)

**Comment by parsonsmatt** [comment]
just gotta wait on CI and merge it in :smile:

**Pull request merged**
