### PR TITLE
Increase default idle timeout to 600 seconds

### PR DESCRIPTION
**Pull request by MaxGabriel**
Before submitting your PR, check that you've:

- [ ] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

n/a

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by bitemyapp** [comment]
10 minutes is a long time for a default timeout, what happened?

**Comment by MaxGabriel** [comment]
Ah, there’s conversation at https://github.com/yesodweb/persistent/issues/775

**Comment by bitemyapp** [comment]
Seems reasonable now that I understand what this is about.

Ought there be a variant of `createSqlPool` that accepts the extra parameter? `createSqlPool` and `createSqlPool'` is usually how I do this but YMMV. Not sure if you wanted to bother to tackle that or not. I have no objections to this PR either way.

**Comment by MaxGabriel** [comment]
@bitemyapp I think a variant of `createSqlPool` is quite reasonable. I think we should also allow configuring the number of stripes as well. I was kind of thinking a separate data type (e.g. `PoolConfig`) might be nice at that point, but I don't feel strongly about this

**Comment by MaxGabriel** [comment]
Preliminary work on this here: https://github.com/yesodweb/persistent/compare/configurableIdleTimeout?expand=1

**Comment by MaxGabriel** [comment]
Made a draft PR to make this value and stripe size configurable https://github.com/yesodweb/persistent/pull/1098

**Comment by MaxGabriel** [comment]
I think at this point, https://github.com/yesodweb/persistent/pull/1098 is basically complete and obviates this PR

**Comment by parsonsmatt** [comment]
I'll close this one out then.

**Pull request closed without merging**
