### PR TITLE
persistent-template: Fix for a *very* late change in ghc-8.0 TH api

### PR DESCRIPTION
**Pull request by erikd**
Now builds with release candidate 4 of the 8.0.1 release.

### CODE REVIEW

**Comment by erikd** [comment]
Would be nice to have a 2.1.8 release of persistent-template as well.

**Comment by gregwebs** [comment]
thanks!

**Comment by gregwebs** [comment]
Thanks. released this and 2.1.8

**Comment by erikd** [comment]
Awesome! Thanks.

**Pull request merged**
