### PR TITLE
Add pool creation functions for `RawSqlite`.

### PR DESCRIPTION
**Pull request by merijn**
Before submitting your PR, check that you've:

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by merijn** [comment]
I still need to test this, but I don't suspect any problems.

**Comment by merijn** [comment]
Seems to work fine in my codebase!

**Comment by parsonsmatt** [comment]
This all looks great to me

**Comment by parsonsmatt** [comment]
Released in `persistent-sqlite-2.10.6`, thanks so much! :smile:

**Pull request merged**
