### PR TITLE
Privilege check (Fix #390)

### LINKED ISSUE #390: check for permissions before starting migration
See this thread for details: https://groups.google.com/d/msg/yesodweb/txpHU5Xi_-E/h_do1trsLsQJ

Goal: run a query along the following lines to ensure we have permissions to view all information on a schema before starting a migration to ensure more usable error messages:

```sql
SELECT grantee, privilege_type FROM information_schema.role_table_grants WHERE table_name = ? AND grantee = CURRENT_USER;
```

### PR DESCRIPTION
**Pull request by psibi**

### CODE REVIEW

**Comment by snoyberg** [comment]
What is this providing over the previous approach of simply trying to perform the operation?

**Comment by psibi** [comment]
@snoyberg This checks if the current user has proper privilege. If it doesn't, it exits with this message:

```
Exiting: You have insufficient privilege for migration.
```
Previously, it used to throw up an unhelpful error message. But after this [patch](https://github.com/yesodweb/persistent/pull/501), it used throws a much better error message IMO:

```
SqlError {sqlState = "42501", sqlExecStatus = FatalError, sqlErrorMsg =
"must be owner of relation person", sqlErrorDetail = "", sqlErrorHint =
""}```

Either way, I don't have a strong opinion on this patch. I thought this was the best way to close up the issue #390. :)

**Comment by snoyberg** [comment]
My concern is that:

* The previous error message was a bit daunting, but still gives the information you need (you're not the owner)
* There's a real possibility that the permission check you've written may have corner cases that aren't handled correctly and will require maintenance going forward, especially for new PostgreSQL versions

**Comment by psibi** [comment]
No issues, I will close this and the corresponding issue then.

**Pull request closed without merging**
