### PR TITLE
Support FKs to non-Int PK entities

### PR DESCRIPTION
**Pull request by pseudonom**
Currently, a declaration like

```haskell

import ClassPrelude.Yesod
import Data.UUID (UUID)

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
  Foo
    Id UUID
  Bar
    fooId FooId
|]
```
will produce bad entity definitions. e.g. The migration will fail with

```
SqlError {sqlState = "42804", sqlExecStatus = FatalError, sqlErrorMsg = "foreign key constraint \"bar_foo_id_fkey\" cannot be implemented", sqlErrorDetail = "Key columns \"foo_id\" and \"id\" are of incompatible types: bigint and uuid.", sqlErrorHint = ""}
```
.

This patch is is currently in the "works for me" stage, though it's pretty ugly. We have to do the fixing at the last minute because otherwise we end up referring to `FooId` before it's been defined.

### CODE REVIEW

**Comment by gregwebs** [comment]
Hmm, there is a test case for a primary key that works now in PrimaryTest.hs. I think you can do something like this right now

```
Foo
  uuid UUID sql=id
  Primary uuid
Bar
  fooId FooId
```

**Comment by pseudonom** [comment]
Oh, interesting. What are the intended use differences between `Id` and `Primary`?

**Comment by gregwebs** [comment]
`Primary` was designed for specifying a multiple column primary key. I will look at this PR soon, because what you are trying to do should definitely be supported

**Comment by gregwebs** [comment]
I added the test schema definition on this branch: https://github.com/yesodweb/persistent/pull/589

**Comment by pseudonom** [comment]
Great, thanks!

**Pull request closed without merging**
