### PR TITLE
Add functions to get PersistEntity instances from JSON instances

### PR DESCRIPTION
**Pull request by andrewthad**
https://github.com/yesodweb/persistent/issues/422

### CODE REVIEW

**Comment by creichert** [comment]
Just a heads up that the patch doesn't recognize you're account as the commiter (although it is under you're name). Not sure if that's intentional or not.

**Comment by creichert** [comment]
Looks great. Is there a plan to support these in derivePersistFieldJSON like @gregwebs  suggested? Might also help to add the actual `instance` declaration snippet to to the haddocks.

**Comment by andrewthad** [comment]
Ah! Thanks. I didn't realize the actual meaning of @gregwebs suggestion until you rephrased it. I don't actually know how to define template haskell functions at all, but I could take a stab at updating `persistent-template` after this gets merged in. I'll update the docs to put in an example, and I think I'm going to tweek the implementation one more time.

Also, thanks for the heads up about github not recognizing me as the commiter. I'll try to figure out how I did that and then not do it again.

**Comment by creichert** [comment]
@andrewthad I went ahead and added the doc examples. Do you want to change the commiter at all before merging?

**Comment by andrewthad** [comment]
Thanks. I looked into how to change the commiter, and I'll pass on changing it now. I think I would have to do force push, and I'm timid when it comes to doing that kind of thing. Feel free to go ahead and merge it in.

**Comment by creichert** [comment]
Awesome patch, I'm looking forward to this one. Can this branch be safely deleted?

**Pull request merged**
