### PR TITLE
Make it build with ghc 9.10

### PR DESCRIPTION
**Pull request by erikd**
This still contains an `allow-newer` stanze that should be remove before this PR can be merged.

There are also quite a lot of compiler warnings that should be fixed at some time.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Are there links to upstream PRs for the `allow-newer`? Or are they just Hackage revisions waiting?

**Comment by erikd** [comment]
> Are there links to upstream PRs for the `allow-newer`? Or are they just Hackage revisions waiting?

I have raised issues from both. They have been waiting on a cabal release.

**Comment by erikd** [comment]
Removed the `allow-newer` stanzas that I added. Ready to go.

**Comment by erikd** [comment]
There are some compiler warnings.

**Comment by parsonsmatt** [comment]
This is great, thanks! I'll make a point release for the affected packages.

**Pull request merged**
