### PR TITLE
Relax template-haskell upper bound for persistent

### PR DESCRIPTION
**Pull request by mpilgrem**
GHC 9.6.1 ships with `template-haskell-2.20.0.0`.

Tested by building the `persistent` library on Windows with Stack and the `stack.yaml`:
~~~yaml
resolver: lts-20.15

packages:
  - ./persistent
  - ./persistent-sqlite
  - ./persistent-test
  - ./persistent-mongoDB
  - ./persistent-mysql
  - ./persistent-postgresql
  - ./persistent-redis
  - ./persistent-qq

extra-deps:
# template-haskell-2.20.0.0 is currently only a candidate package on Hackage
- url: https://hackage.haskell.org/package/template-haskell-2.20.0.0/candidate/template-haskell-2.20.0.0.tar.gz
- ghc-boot-th-9.6.1
# Accepts template-haskell-2.20.0.0
- aeson-2.1.2.1
- generically-0.1.1
- tagged-0.8.7
# GHC boot packages
- bytestring-0.11.4.0
- text-2.0.2
- binary-0.8.9.0
- exceptions-0.10.7
~~~

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Do you mind adding GHC 9.6 to the CI for this? Code here: https://github.com/yesodweb/persistent/pull/1485 

Tempted to merge as-is but would like to know it's safe

**Comment by mpilgrem** [comment]
@parsonsmatt, I've updated the CI matrix. I took the liberty of also bumping the GHC 9.2.x and 9.4.x series.

**Comment by mpilgrem** [comment]
I see you have already taken action on the `cryptohash-md5` dependency and GHC 9.6.1: https://github.com/haskell-hvr/cryptohash-md5/pull/15

**Comment by mpilgrem** [comment]
There is a revision 2 to `cryptohash-md5-0.11.101.0` on Hackage, but for some reason the CI did not appear to acknowledge it.

**Pull request merged**
