### PR TITLE
Migration fix

### PR DESCRIPTION
**Pull request by merijn**
New PR against master for the persistent-sqlite 2.11.1 .0 changes from #1184

Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by merijn** [comment]
Looks like postgres tests are broken for some reason?

**Comment by parsonsmatt** [comment]
I've fixed CI, mind rebasing and trying again?

**Comment by merijn** [comment]
hmm, rebasing is tricky, since I merged with master to get the conflicting changes from master solved. I think remerging master is probably less work, especially given my weak git-fu.

**Comment by merijn** [comment]
Hmm, I'm unsure why 8.4 fails on the string literal in that code, 8.6.5 and 8.10.2 work fine locally and after staring at the code for 10 minutes I conclude: It *is* legal Haskell and I have no idea why 8.4 is choking.

**Comment by merijn** [comment]
I had an epiphany! The breakage is due to master having CPP enabled and using the C/C++ CPP on Haskell code (as GHC does currently) being insanity...

**Comment by parsonsmatt** [comment]
Thanks so much 😄

**Pull request merged**
