### PR TITLE
Support for mongoDB 2.1

### PR DESCRIPTION
**Pull request by snoyberg**
Pinging @gregwebs and @psibi, relevant to #597. The fact that I could work around this in this manner means to me that the mongoDB library made a mistake in their API change.

### CODE REVIEW

**Comment by psibi** [comment]
This looks way better. Have you intentionally not added the `MonadBaseControl` constraint to the `runMongo` function ? Will the tests work if mongoDB version constraint is bumped to 2.1.0. ? The Travis test for this repository was passing successfully previously. The nix hydra servers were failing for this package because it was picking the new version of `mongoDB`.

**Comment by snoyberg** [comment]
I haven't experimented with the tests, but I did locally test against the new version of mongoDB. We can always bump the version number in the stack.yaml file, I have no opinion on that.

The trick going on here is that, instead of having a `MonadBaseControl` constraint, I've just constrained the monad in the argument (i.e., in negative position) to `IO`. This fulfills the `MonadBaseControl` constraint, and then I can just `liftIO` the resulting action back into the external monad.

I don't have time for it, but ideally I would have sent a PR upstream to mongoDB to make the change there. Ideally, all functions would have a signature like one of the following:

```haskell
foo :: MonadIO m => arg -> Action m res
foo :: (MonadIO m, MonadReader MongoContext m) => arg -> m res
```

The reason this works is that, AFAICT, there is never a reason to have the base monad in negative position (such as with a callback function or an exception handler).

**Comment by gregwebs** [comment]
@VictorDenisov lets look at fixing this upstream

**Comment by VictorDenisov** [comment]
Ok. Looking into it.

**Comment by VictorDenisov** [comment]
I think I understood the concept. I can do this trick in mongodb. I'll release another version of mongodb by the end of this week.

**Comment by VictorDenisov** [comment]
Published https://hackage.haskell.org/package/mongoDB-2.1.1. It shouldn't have MonadBaseControl for functions modified in 2.1.0.1. I also see that some of functions still have MonadBaseControl. We can remove those restrictions in later versions.

**Pull request closed without merging**
