### PR TITLE
fix postgres array serialization

### PR DESCRIPTION
**Pull request by eryx67**
convert PersistList to Database.PostgreSQL.Simple.Types.PGArray instead of JSON

### CODE REVIEW

**Comment by gregwebs** [comment]
This could be a good change if Postgres is flexible enough in its array storage. We have tests for a lot of different use cases, and some of them are failing with this change.

**Comment by gregwebs** [comment]
#411 should cover this use case even if using a PGArray is more ideal for simple array use cases.

**Comment by Vlix** [comment]
I've added PersistentArray to get the `array[]` syntax in [#863](https://github.com/yesodweb/persistent/pull/863), but that was to make the JSON operators work.
I don't know if it's desireable for `PersistList` to just use the `array[]` syntax, but I think I could integrate that change into my PR and drop the new `PersistArray` data constructor.
I saw PersistList using JSON marshalling so just thought it'd be better not to touch it, to be honest.

If anyone has an opinion about this, do share.

**Comment by parsonsmatt** [comment]
I'm in favor of closing this one for #863 . Changing how `PersistList` is serialized seems like a bigger potential for breaking than I'd like to incur.

**Pull request closed without merging**
