### PR TITLE
Test Stackage lts-15 and lts-16 on CI

### PR DESCRIPTION
**Pull request by sol**

### CODE REVIEW

**Comment by MaxGabriel** [comment]
This seems good to me. Possibly we should think about dropping support for 8.2 as well

**Comment by sol** [comment]
Is there anything specific that I can do to help move this forward?

**Comment by MaxGabriel** [comment]
ah, yes, sorry. Do you mind bumping the version of Persistent-mongoDB in the .cabal file, and adding a line to the changelog?

**Comment by parsonsmatt** [comment]
I'm fine publishing a revision and accepting as-is

**Pull request merged**
