### PR TITLE
Switch Travis to use VM environments to solve random test timeouts

### PR DESCRIPTION
**Pull request by paul-rouse**
See issue #710

### CODE REVIEW

**Comment by psibi** [comment]
IIRC, Michael moved travis from sudo enabled to container one explicitly to decrease build times.

**Comment by paul-rouse** [comment]
I think this was a question of whether you can cache builds, which I believe used to be available only in the container environment.  As far as I can tell, this has changed, and caching now works in sudo-enabled builds as well - I did test a repeated build from my fork of persistent, and the second build really did go a lot faster.

Does that answer your concern?

**Comment by paul-rouse** [comment]
Yes, a repeat run does go a good deal faster (3 or 4 times), so caching is certainly working.  The actual times look OK to me, too - do you agree @psibi?

**Comment by psibi** [comment]
Yeah, the travis output looks good and caching is actually working. Free feel to merge.

**Comment by paul-rouse** [comment]
Thanks for looking at it!

**Pull request merged**
