### PR TITLE
Add example usages to upsert, upsertBy, repsert

### PR DESCRIPTION
**Pull request by pythonissam**
Before submitting your PR, check that you've:

- [ ] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by pythonissam** [comment]
ref: https://github.com/yesodweb/persistent/issues/817

**Comment by psibi** [comment]
@pythonissam LGTM. You can add further examples for other functions if you feel like so. Let me know when it is ready for review.

**Comment by pythonissam** [comment]
@psibi I understand. Thank you!

**Comment by pythonissam** [comment]
@psibi I've added additional examples, yet I'm going to add more...

Would you check them for now? You can use a template below to test functions:

``````

**Comment by pythonissam** [comment]
@psibi Done. Would you review it?

**Comment by psibi** [comment]
Give me two days, I will review it if nobody else has done it by then.
Currently on a travel.

**Comment by pythonissam** [comment]
@psibi Of course. Have a nice trip:)

**Comment by psibi** [comment]
@pythonissam Thanks for your work on this. Can you try running `stack haddock persistent` and see the Haddocks for yourself once ?

When I executed that on my local machine, your examples doesn't seem to be appearing. Also - both `PersistStore` module and `PersistUnique` module's doc seem to be repeated in the `Class` module as it seems to reference them. Can you update your PR with the appropriate fixes ?

Thanks for working on this!

**Comment by psibi** [comment]
Sorry, I'm on a trip right now and don't have access to laptop till 27th.
Will look into it after that if nobody get backs to you by it.

**Comment by psibi** [comment]
@pythonissam Thanks, running haddock again made it work. Your examples looks good, but I think it would be better if it would be consistent with the already existing haddock of `Database.Persist` module. Instead of showing this:

```
spj <- get spjId
```

If you can define a local function:

```
getSpj :: MonadIO m => Int64 -> ReaderT SqlBackend m ()
getSpj id = get id
```

And then show the results in the form of a table instead of showing it like `fromList`. Note that the above code is just for illustration and won't even compile. Let me know if you have any concerns.

**Comment by pythonissam** [comment]
@psibi 

> but I think it would be better if it would be consistent with the already existing haddock of `Database.Persist` module

> And then show the results in the form of a table instead of showing it like fromList

No objection. Okay, I'll modify examples accordingly.

**Comment by psibi** [comment]
@pythonissam 

I was think along something like this:

```
#!/usr/bin/env stack
-- stack script --resolver lts-11.6

{-# LANGUAGE EmptyDataDecls             #-}
{-# LANGUAGE FlexibleContexts           #-}
{-# LANGUAGE GADTs                      #-}
{-# LANGUAGE GeneralizedNewtypeDeriving #-}
{-# LANGUAGE MultiParamTypeClasses      #-}
{-# LANGUAGE OverloadedStrings          #-}
{-# LANGUAGE QuasiQuotes                #-}
{-# LANGUAGE TemplateHaskell            #-}
{-# LANGUAGE TypeFamilies               #-}

import           Control.Monad.IO.Class  
import Control.Monad.Reader
import           Database.Persist
import           Database.Persist.Sqlite
import           Database.Persist.TH

share [mkPersist sqlSettings, mkMigrate "migrateAll"] [persistLowerCase|
User
    name String
    age Int
    deriving Show
|]

getSpj :: (MonadIO m) => (Key User) -> ReaderT SqlBackend m (Maybe User)
getSpj spjId =  get spjId

main :: IO ()
main = runSqlite ":memory:" $ do
  runMigration migrateAll

  liftIO $ putStrLn ""

  (spjId:_) <-
    insertMany [User "SPJ" 40, User "Simon" 41]

  newRecs <- getSpj spjId
  liftIO $ print newRecs
  liftIO $ putStrLn ""
```

See the `getSpj` function above. The specialized type signature IMO gives a better idea to the users of the library.

> Excuse me, but I don't fully understand this. You mean "We should use completely different examples since docs seem to be repeated"?

Ignore my comment regarding that. My haddock wasn't properly built when I commented that. The examples are looking great so far!

**Comment by pythonissam** [comment]
Aha, I understand. It seems nice. OK, I'll do so:)

**Comment by pythonissam** [comment]
@psibi I completely figured out what you meant. Latest commit may be quite large though, can I ask you to review updated docs?

**Comment by psibi** [comment]
Thanks! Merged.

**Comment by pythonissam** [comment]
Yay! Thank you for reviewing:)

**Pull request merged**
