### PR TITLE
Add type application to `selectList` documentation.

### PR DESCRIPTION
**Pull request by friedbrice**
Before submitting your PR, check that you've:

- [x] Ran `stylish-haskell` on any changed files.
- [x] Adhered to the code style (see the `.editorconfig` file for details)

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by friedbrice** [comment]
Hmm, the [build failure](https://github.com/yesodweb/persistent/runs/6043702882?check_suite_focus=true#step:15:223) appears to be unrelated to my change.

**Comment by friedbrice** [comment]
@parsonsmatt Thanks for re-running my build. It's a strange error. If I'm reading it right, it says they're a missing shared library? How, even? FWIW (though I know it's not much), the project builds on my machine with GHC 9.0.x

**Comment by parsonsmatt** [comment]
urge to switch back to `stack` based build rising

**Comment by friedbrice** [comment]
@parsonsmatt Passed CI under GHC 9.0.2 :-D

**Comment by parsonsmatt** [comment]
Thanks! 😄

**Pull request merged**
