### PR TITLE
Split read and write capabilities

### PR DESCRIPTION
**Pull request by pseudonom**
This may resolve some of the build issues in https://github.com/yesodweb/persistent/pull/534.

### CODE REVIEW

**Comment by pseudonom** [comment]
Woo, looks like we finally fixed it. Is this good to go once https://github.com/phadej/aeson-compat/pull/8 gets merged?

**Comment by psibi** [comment]
@pseudonom Is there any specific reason why you are adding `aeson-compat` source inside the repository ?

**Comment by pseudonom** [comment]
It was a temporary wayto fix the build while waiting on https://github.com/phadej/aeson-compat/pull/8.

**Comment by pseudonom** [comment]
Okay, devendored `aeson-compat`. Anything else left to do?

**Comment by pseudonom** [comment]
And I can write docs, explanatory post, etc. once we decide to actually merge this, if that helps.

**Comment by gregwebs** [comment]
I like the last commit.

Does it make sense to add an alias for the following?

```
BaseBackend backend ~ SqlBackend, IsPersistBackend backend
```

Perhaps `SqlPersistBackend` ?

Other than that, this is just missing a major version bump for persistent?

**Comment by pseudonom** [comment]
Good call on the additional synonym; there were quite a few of those. I called it `IsSqlBackend`. That make sense to you?

And yeah, assuming that those last travis fixups are good, this should all be ready to go.

**Comment by pseudonom** [comment]
Okay, travis is all fixed up. I think this should be totally ready.

**Comment by gregwebs** [comment]
Are there known backwards compatibility issues or in theory is this all compatible?

@snoyberg any feedback?

**Comment by pseudonom** [comment]
There's a bit of backwards incompatibility for library authors. You can see some examples in https://github.com/yesodweb/yesod/pull/1157/files. They basically all revolve around the fact that now `BaseBackend backend ~ PersistEntityBackend val` instead of the old `backend ~ PersistEntityBackend val`. 

This shouldn't affect application developers as long as they're not trying to wrap/re-expose `persistent` in full generality.

**Comment by snoyberg** [comment]
No feedback from me. If this adds in helpful functionality with a relatively small downstream breakage, I'm OK with it.

**Comment by pseudonom** [comment]
Great! What's the next step?

**Comment by gregwebs** [comment]
I will merge & release this as a new major version some time this weekend. If you can make sure documentation is good, that would be great. That can include a blog post (you can recycle content) that we can publish on the yesodweb blog.

**Comment by pseudonom** [comment]
Hurray. Working on the docs and blog post now.

**Comment by pseudonom** [comment]
Okay. Added some more docs and blog post PR out now: https://github.com/yesodweb/yesodweb.com-content/pull/165.

**Comment by gregwebs** [comment]
Thanks for the great changes and the blog post! I will version bump and release now

**Comment by gregwebs** [comment]
This is released now as 2.5

**Pull request merged**
