### PR TITLE
Support new conduit release

### PR DESCRIPTION
**Pull request by snoyberg**
The new version of conduit (1.3) is going to be released soon, and will be switching from `monad-control` over to `unliftio-core`. This PR moves the persistent API over as well for compatibility, while still keeping compatibility with the older version (though Travis may discover a few things I still need to tweak to make this work). It also drops usage of deprecated operators and type synonyms in conduit 1.3, and cleans up a few other warnings.

Is there any objection to me merging this and making a new major release of persistent, persistent-sqlite, persistent-postgresql, persistent-mysql, and persistent-mongoDB when I'm releasing the new version of conduit?

### CODE REVIEW

**Comment by MaxGabriel** [comment]
I'm good with that. There are a few PRs that were waiting on a breaking change for their release:

* #760 
* #734
* Revert #759, which itself had reverted an accidental breaking. I'm good with that. There are a few PRs that were waiting on a breaking change for their release:

**Comment by snoyberg** [comment]
Alright, I've merged both #760 and #734 into this branch, and I've reverted #759. Can you mind giving those last commits a review to ensure I hit what you were looking for? Also, CC @parsonsmatt.

**Comment by MaxGabriel** [comment]
Didn’t look over too closely but it LGTM

**Comment by MaxGabriel** [comment]
I think something was going wrong with the Travis build on this (Travis's UI said it had been running for over 6 hours without any progress) so I killed it

**Comment by snoyberg** [comment]
I've been testing with a megarepo that includes all the deps, since I've been modifying all of the repos in lock step. The new conduit version isn't yet on Hackage. I've pushed a commit that adds appropriate extra-deps to hopefully get this compiling.

**Comment by rwobben** [comment]
When I want to clone this repo ,to make the drop ghc part, how is this branch named.

**Comment by MaxGabriel** [comment]
@ghost it’s named newer-conduit

**Pull request merged**
