### PR TITLE
Sqlite upgrade to 3.22.0

### PR DESCRIPTION
**Pull request by joncfoo**
Before submitting your PR, check that you've:

- [x] Bumped the version number

After submitting your PR:

- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by joncfoo** [comment]
I also have another branch based on this PR that I'd like to submit though I'm not sure what the best way to do that is - https://github.com/joncfoo/persistent/tree/sqlite-enable-common-extensions

Thoughts?

**Comment by MaxGabriel** [comment]
You can submit the second PR. I’ll merge the first and then we can merge the second (you may have to rebase the second against master after we merge the first, not sure if there’ll be merge conflicts).

These are great PRs btw! Thanks for contributing

**Comment by MaxGabriel** [comment]
I’m on a ski trip this weekend and will probably be able to merge this on Monday

**Comment by joncfoo** [comment]
Happy to contribute as I need this functionality as well :smile:

**Comment by MaxGabriel** [comment]
@joncfoo I noticed [your commit that applies the stat64 workaround](https://github.com/yesodweb/persistent/pull/789/commits/2027b575cf206451b44713ef3d7574c5b73f3361) doesn't actually change any SQLite code to call those new functions, like [Michael's commit did](https://github.com/yesodweb/persistent/commit/0df11d70e936389ca6ed15afb227f6224ad16f22). Is that intentional?

**Comment by MaxGabriel** [comment]
Hm, I notice that the [GHC ticket](https://ghc.haskell.org/trac/ghc/ticket/7072) the workaround was meant for is now closed, so potentially we can just not have this workaround at all.

**Comment by joncfoo** [comment]
Oh, I did not apply the call-site patch!

Since the GHC ticket is closed regarding the stat64 workaround should I revert the extraneous addition to cbits?  Is there a good way to test the workaround is not needed (IIRC this issue affected macOS as well but I don't have a macOS machine)?

**Comment by MaxGabriel** [comment]
@joncfoo I'll test macOS

**Comment by MaxGabriel** [comment]
@joncfoo Ok, I was able to load persistent-sqlite in a repl from your branch (`stack repl persistent-sqlite`) and also wasn't able to reproduce with the reproduction code in the GHC ticket (`cabal build`, `cabal repl lib:stat-test`). And it seems like Linux is working because the GHC ticket is closed.

So here's what I propose: You delete your stat64 workaround code, and also delete the part of `development.md` that says to make this change.

Also: big thanks for helping remove this legacy cruft!

**Comment by joncfoo** [comment]
I've updated the code.  I'm happy to contribute!  Thanks for looking into the stat64 workaround.  I'm glad we no longer need to do this.

**Comment by MaxGabriel** [comment]
@joncfoo Released 👍

**Pull request merged**
