### PR TITLE
Split persistent into read and write classes

### PR DESCRIPTION
**Pull request by pseudonom**
As discussed in https://github.com/yesodweb/persistent/issues/518

### CODE REVIEW

**Comment by pseudonom** [comment]
I assume the next step would be to newtype `SqlBackend` as `ReadSqlBackend` and `WriteSqlBackend`?

**Comment by erikd** [comment]
I'd probably name them `SqlReadBackend` and `SqlWriteBackend`.

**Comment by pseudonom** [comment]
Example of use in https://github.com/pseudonom/splitdb/commit/cf52fd4c94123c2094dd54851742077e086addd2.

Not sure what's going on with Travis CI.

**Comment by pseudonom** [comment]
Can anyone give me hints on Travis? This definitely builds locally and almost all the tests pass.

**Comment by snoyberg** [comment]
Looks like it's because aeson-compat was removed from the test suite dependencies:

https://github.com/yesodweb/persistent/pull/534/files#diff-777410b9e6ac65f07fdf95f2f223f38bL135

**Comment by pseudonom** [comment]
Huh, I removed it because it seemed to be causing problems locally (it was, I think, overlapping with `aeson-extra`) I can try readding it tomorrow.

**Comment by pseudonom** [comment]
Ah, looks like the underlying issue may have been that I was using `stack` and the desired development flow involves `cabal`?

**Comment by snoyberg** [comment]
We test with cabal on Travis, which is probably pulling in newer versions
of dependencies than you're getting with Stack.

**Comment by pseudonom** [comment]
Now it looks like there's a linker error for the new module (which I did add to `persistent`'s cabal file). Is that anything you've encountered before?

**Comment by snoyberg** [comment]
You added it to persistent-test as well?

**Comment by pseudonom** [comment]
Ah, I did not. Thanks, I'll try that tomorrow.

**Comment by pseudonom** [comment]
Hm, some of the runs are timing out during compile of `EmbedTest` now...

**Comment by gregwebs** [comment]
@pseudonom awesome!

I am wondering if there are any shorthands that make sense to add to the code base itself?
I am having a hard time coming up with them though. For example

```
type PersistEntityBaseBackend = (BaseBackend backend ~ PersistEntityBackend val, PersistEntity val)
```

Doesn't seem like a huge win yet.

If the only outstanding issue is getting Travis to build, we can definitely help you though it. Do we need to increase the timeout a bit? persistent may have been on the edge of timing out already.

**Comment by pseudonom** [comment]
Yeah, no shorthands immediately jump out at me. Fortunately, shouldn't be too hard to add them later if we discover we want some?

I'm not sure if increasing the timeout would help. Travis is getting
```
[30 of 50] Compiling EmbedTest        ( EmbedTest.hs, dist/build/EmbedTest.o )
No output has been received in the last 10 minutes, this potentially indicates a stalled build or something wrong with the build itself.
```
but it doesn't take anything close to 10 minutes to compile `EmbedTest` locally. Is it possible that GHC is hanging in some way that's configuration dependent?

**Comment by gregwebs** [comment]
It could be hitting memory limits now. We have seen cases of that in the past.

**Comment by pseudonom** [comment]
Is bumping the memory limit something I can do?

**Comment by pseudonom** [comment]
Any hints about what I can do here?

**Comment by pseudonom** [comment]
Closing in favor of https://github.com/yesodweb/persistent/pull/546

**Pull request closed without merging**
