### PR TITLE
Changed persistent-mysql to use 'utf8mb4' instead of 'utf8' in migrations

### PR DESCRIPTION
**Pull request by charukiewicz**
As stated in title, this changes migration behavior for the `VARCHAR` and `TEXT` column types to use the `uft8mb4` character set as opposed to `uft8`. This is because [`utf8` is an alias for `utf8mb3` which does not properly handle all UTF-8 strings](https://dev.mysql.com/doc/refman/8.0/en/charset-unicode-utf8.html). Here's another [StackOverflow answer that discusses this](https://stackoverflow.com/questions/202205/how-to-make-mysql-handle-utf-8-properly).

Not sure if this is worth a version number bump, as `utf8mb4` is fully backwards compatible. Let me know if I should bump the version.

-------

Before submitting your PR, check that you've:

- [ ] Bumped the version number

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
I'm happy with this change. Is it a drop-in 100% improvement with no possible breaking change behavior?

**Comment by charukiewicz** [comment]
As far as I know, yes. `utf8mb4` is a superset of what MySQL calls `utf8`, which is an alias for `utf8mb3`. This means a maximum of 4 bytes instead of 3 bytes. Everything else will work the same way.

**Comment by parsonsmatt** [comment]
awesome! I'll try to get this released this weekend.

**Comment by parsonsmatt** [comment]
Released as `persistent-2.10.2.1`

**Pull request merged**
