### PR TITLE
Allow aeson 1.5

### PR DESCRIPTION
**Pull request by felixonmars**
Builds fine and all tests pass here.

### CODE REVIEW

**Comment by parsonsmatt** [comment]
Why'd you delete all the "things to do before/after submitting a PR"? I'd like to have a CHANGELOG entry and version bump for this - patch should do fine. Thanks!

**Comment by felixonmars** [comment]
I thought it is not worth a version bump but only a revision, so I removed all of them. I'll update now.

**Comment by jkachmar** [comment]
Ping re. commercialhaskell/stackage#5393, anything blocking this from being merged that I could help out on?

**Comment by parsonsmatt** [comment]
Thanks for the ping - this LGTM and I'm happy to incorporate + make a HAckage revision.

**Pull request merged**
