### PR TITLE
Allow GHC 9.2 for compatible packages

### PR DESCRIPTION
**Pull request by ysangkok**
This is based on #1338 but avoids overriding dependencies. The compatible targets are built and tested in CI, ~~the others are marked as unbuildable and cabal-install will just skip them.~~ EDIT: nothing is disabled any more

### CODE REVIEW

**Comment by ysangkok** [comment]
@parsonsmatt The PR now enables all packages since Cryptonite was updated.

**Review by parsonsmatt — APPROVED** [review]

**Comment by parsonsmatt** [comment]
Thank you!

**Comment by parsonsmatt** [comment]
Looks like we just need a patch level change on `persistent` and `persistent-{mysql,mongoDB,postgresql,redis}` for this one. I'll work up the changelog and cabal patches and have this released today.

**Comment by parsonsmatt** [comment]
Going to merge into my branch and finish it off, thanks!

**Pull request merged**
