### PR TITLE
Add insertEntity

### LINKED ISSUE #376: Adding an "insertEntity :: e -> DB (Entity e)" helper
I'd like to add the following function:

```hs
insertEntity :: (PersistEntity e, PersistEntityBackend e ~ SqlBackend)
             => e -> DB (Entity e)
insertEntity e = fmap (\eid -> Entity eid e) $ insert e

-- where DB is a synonym I've been using:
type DB a = forall (m :: * -> *).
    (MonadIO m, Functor m) => ReaderT SqlBackend m a
```

(I'd like to add the synonym too, but that can be a separate discussion)

`insertEntity` allows you to take code like:

```hs
let foo = buildFoo
fooId <- runDB $ insert foo
```

And make it:

```hs
Entity fooId foo <- runDB $ insertEntity buildFoo
```

I've had frequent use for this in test suites, and could also picture it in creation Handlers (e.g `Entity fooId foo <- runDB . insertEntity =<< requireJsonBody`).

Before I start on a PR, I'd like to know:

1. This doesn't already exist, right?
1. Is the name OK?
1. Can `DB` be generalized beyond `SqlBackend`
1. In what module would this most make sense?

Thanks

### PR DESCRIPTION
**Pull request by pbrisbin**
- Like insert, but returns a complete Entity
- Resolves #376

### CODE REVIEW

**Comment by gregwebs** [comment]
Great, pretty sure I wrote this one myself before and forgot to push it upstream. Can you add a test case? If you want you can rely on Travis to execute it.

**Comment by pbrisbin** [comment]
I wanted to, but didn't see any similar tests [here](https://github.com/yesodweb/persistent/blob/master/persistent/test/main.hs) -- is there another place to look/add to?

**Comment by gregwebs** [comment]
All the tests that use backends are in persistent-tests. You could put your test around here: https://github.com/yesodweb/persistent/blob/master/persistent-test/PersistentTest.hs#L657

**Comment by pbrisbin** [comment]
Cool, will do

**Comment by pbrisbin** [comment]
Test added and green. Let me know if this is good and I'll rebase/merge.

**Comment by gregwebs** [comment]
looks great, thanks!

**Pull request merged**
