### PR TITLE
Allow Postgres migrations to enable extensions

### PR DESCRIPTION
**Pull request by enolan**
This is kind of ugly, I'm happy to take feedback.

### CODE REVIEW

**Comment by MaxGabriel** [comment]
@enolan Why not just run `CREATE EXTENSION IF NOT EXISTS` instead of checking, then running? I think that would simplify the code greatly.

**Comment by enolan** [comment]
That's what I had originally, but it means that the migration always prints when you start your program, which is a little annoying and a little confusing.

**Comment by MaxGabriel** [comment]
@enolan I think this is a good PR then. Can you bump the version number of the cabal file and add a changelog entry?

**Comment by enolan** [comment]
I bumped the version number and added a changelog entry. Something weird is happening with Travis, but I'm pretty sure it has nothing to do with my code.

**Comment by MaxGabriel** [comment]
Merged! Thanks for your contribution :)

**Pull request merged**
