### PR TITLE
Added support for GHC 8.8 in persistent. MonadFail should be used.

### PR DESCRIPTION
**Pull request by varosi**

### CODE REVIEW

**Comment by varosi** [comment]
Related to #958 and fixes import problem

**Comment by parsonsmatt** [comment]
Awesome, thanks!!

**Comment by varosi** [comment]
Thank you, too!

**Comment by varosi-chaosgroup** [comment]
Is it possible someone with access to upload this new version to Hackage?

**Comment by parsonsmatt** [comment]
I will get that done today.

**Comment by parsonsmatt** [comment]
2.10.3 is released with this patch. Thanks!

**Comment by varosi** [comment]
It's interesting that even thou it is in Hackage, still for two days it's not visible in Stackage.

**Comment by varosi** [comment]
#977

**Pull request merged**
