### PR TITLE
Change SQL functions to use `BackendCompatible` over `IsSqlBackend`.

### PR DESCRIPTION
**Pull request by merijn**
This addresses #783 so that #772 can be updated to use this and finally be merged.

### CODE REVIEW

**Comment by merijn** [comment]
I'm not sure if/how this breaks the non-sqlite persistents, as I can't get them to build reliably on my system anyway. We'll see what CI says.

**Comment by parsonsmatt** [comment]
@merijn This PR looks like a good start, but we'll need to continue propagating the changes through so that CI passes.

**Comment by merijn** [comment]
@parsonsmatt If someone else is willing to take over the PR that'd probably be the best way to make progrss, as I'm basically swamped in real life at the moment. I can keep an eye on any related PRs/changes and chime in if needed, but can't really dedicate a bunch of time to fixing up the other persistent packages.

**Comment by Vlix** [comment]
I could see if I can go through all the non-SQLite backends and just propagate these changes next time I feel like I need some distraction.
Is it basically replacing all `IsSqlBackend` with `BackendCompatible SqlBackend`?

**Comment by merijn** [comment]
@Vlix Basically, yes. `IsSqlBackend` is unnecessarily restrictive. See also the discussions linked in my first comment.

**Comment by Vlix** [comment]
I've started working on this, and I think I'm pretty much done, but I've removed most `backend` parameters in the MySQL/PostgreSQL/SQLite libraries where `IsSqlBackend backend` was used, because it was just a `SqlBackend` being `mkPersistBackend`-ed to `backend` to be used as a `SqlBackend`.

Only part that's giving me trouble is the `rawQueryRes` function... changing the `IsSqlBackend` to `BackendCompatible SqlBackend backend` turns into a wild goose chase until I get to `selectKeysRes` and getting rid of `BaseBackend (BaseBackend backend)` seems impossible.

**Comment by parsonsmatt** [comment]
The `BaseBackend (BaseBackend backend)` thing always felt very hacky to me

**Comment by Vlix** [comment]
@merijn
Is there a reason you wanted the `BackendCompatible SqlBackend backend` in the `persistent-sqlite` library constraining the `backend`, instead of it just being a `SqlBackend`?
Going through the types (signatures), just setting it to `SqlBackend` makes the most sense, since it's a SQL DB, and the root function causing it, is `warpConnectionInfo` which literally outputs a `SqlBackend`.

**Comment by merijn** [comment]
@Vlix 
The problem was basically that all the bracket-like functions are very restricted by `IsSqlBackend`, because it requires that any instance can be created/project from *just* an `SqlBackend`. Whereas, for example, the `persistent-sqlite` PR for exposing the internal SQLite pointer carries additional data (i.e. the actual pointer for the SQLite connection) that cannot be recreated from thin air when you have just an `SqlBackend`.

The idea behind the original introduction of `BackendCompatible` was to make the constraints in persistent more flexible, and discussion in the other PR led to going down this road.

**Comment by Vlix** [comment]
I've managed to pretty much remove the need for `IsSqlBackend` from the code base. I hope it didn't break anything... I don't think it should.
My PR is over [here](https://github.com/yesodweb/persistent/pull/886)

**Comment by parsonsmatt** [comment]
Yup, #886 covers this one - I am going to close this PR out since #886 is nearly ready to go.

**Pull request closed without merging**
