### PR TITLE
Add UUID instances for PersistField

### PR DESCRIPTION
**Pull request by jappeace**
Issue: https://github.com/yesodweb/persistent/issues/579

As discussed this only works for postgres. This suggested PR has no support for MySQL.  
An alternative could be creating a newtype as suggested by @parsonsmatt 
I'm not sure what's best. But at least now we have something to point at.

Before submitting your PR, check that you've:

- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [ ] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [ ] Update the Changelog.md file with a link to your PR
- [ ] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by MaxGabriel** [comment]
So, I think this should probably be a newtype and be in the persistent-postgresql package, so other databases could have their own instances.

Possibly UUID could have a PersistField instance in regular `persistent`, and a newtype of _that_ could be in the postgres package for a  `PersistFieldSql` instance. This would work if most databases use the same format for UUIDs (I'm seeing MySQL recommend a binary version of UUIDs, though, so this might not work https://mysqlserverteam.com/mysql-8-0-uuid-support/)

**Comment by jappeace** [comment]
@MaxGabriel 

I'm considering extending the `SqlType` value instead with a SqlUUID constructor. First class support for UUID seems like something many users want, doing it like this essentially gives us the ability to make the best default choice. If a user wants to use a different choice they can still choose to use a newtype downstream.
Using a newtype in this repository works, but it feels more like a workaround. What do you think?

**Comment by parsonsmatt** [comment]
`SqlUUID` is the right point to add it, IMO, since it's not consistent among databases how it is represented.

**Comment by jessekempf** [comment]
@MaxGabriel: Do you really anticipate it would be that difficult for us to infer the encoding, and then decode that? The possible wire encodings boil down to strings, strings without `-` separators, and 16 bytes in either host or network byte order.

**Pull request closed without merging**
