### PR TITLE
fix insertKey with a composite key

### LINKED ISSUE #416: repsert (and insertKey) at least with sqlite does not seem to respect tables that omits an `id` column.
Here's a really simple reproduce with both the `repsert` and by proxy `insertKey` because `repsert` is implemented in terms of `insertKey`

```Haskell
{-# LANGUAGE GADTs, OverloadedStrings, QuasiQuotes, TemplateHaskell, TypeFamilies, DeriveGeneric, FlexibleInstances #-}
import Control.Monad.Except
import Data.Text (Text)
import Data.ByteString (ByteString)

-- Sql stuff
import qualified Database.Persist.TH as P
import Database.Persist.Sql
import Database.Persist.Sqlite hiding (get)

P.share [P.mkPersist P.sqlSettings, P.mkMigrate "migrateSimpleState"] [P.persistLowerCase|
SimpleState
    moduleName  Text
    stateKey    Text
    state       ByteString
    Primary moduleName stateKey
    deriving Show Eq
|]

-- repsert version
setState :: (MonadIO m) => Text -> Text -> ByteString -> SqlPersistT m ()
setState m k v = either
    (\_  -> return ())
    (\k' -> repsert (k' :: Key SimpleState) (SimpleState m k v))
    (keyFromValues [PersistText m, PersistText k])
    
    
test :: IO ()
test = runSqlite ":memory:" $ do
    runMigration migrateSimpleState
    
    setState "a" "b" "c"
    setState "a" "b" "d"
    setState "a" "c" "e"
```

Results:

```
*Karmator.State> :load src/karmator/reproduce.hs 
[1 of 1] Compiling Main             ( src/karmator/reproduce.hs, interpreted )
Ok, modules loaded: Main.
*Main> test
Migrating: CREATE TABLE "simple_state"("module_name" VARCHAR NOT NULL,"state_key" VARCHAR NOT NULL,"state" BLOB NOT NULL, PRIMARY KEY ("module_name","state_key"))
*** Exception: SQLite3 returned ErrorError while attempting to perform prepare "INSERT INTO \"simple_state\"(\"id\",\"module_name\",\"state_key\",\"state\") VALUES(?,?,?,?)": table simple_state has no column named id
```

### PR DESCRIPTION
**Pull request by gregwebs**
closes #416 
@pharaun @mkscrg

### CODE REVIEW

**Comment by MaxGabriel** [comment]
LGTM.

**Comment by MaxGabriel** [comment]
@gregwebs Is this assigned to me to fix the test failures?

**Comment by MaxGabriel** [comment]
This looks to be the root cause of the failures:
```
    Failures:

      1) composite, primary keys, insertWithKey
           uncaught exception: MySQLError (ConnectionError {errFunction = "query", errNumber = 1110, errMessage = "Column 'age' specified twice"})
```

**Comment by gregwebs** [comment]
sorry, I was assigning for review. I still need to finish this.

**Comment by Prillan** [comment]
Any ETA for this? Just got hit by this bug.

Is there anything I can do to fix it?

**Comment by gregwebs** [comment]
This is on hacakge as persistent-2.2.1

**Pull request merged**
