### PR TITLE
Bump versions for postgresql-simple and postgresql-libpq

### PR DESCRIPTION
**Pull request by Vekhir**
Builds and tests fine

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Bumped the version number if there isn't an `(unreleased)` on the Changelog
- [ ] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by parsonsmatt** [comment]
I've made Hackage Revisions to this effect. Thanks!

**Comment by Vekhir** [comment]
Do Hackage revisions need some time? I don't see the revisions on either [2.13.5.2](https://hackage.haskell.org/package/persistent-postgresql-2.13.5.2) nor [2.13.6](https://hackage.haskell.org/package/persistent-postgresql-2.13.6).
Also unfortunate that this PR didn't make it into 2.13.6.

**Comment by Vekhir** [comment]
Tbh, I get the impression that you accidentally released 1.13.6 instead of a Hackage revision?

**Comment by parsonsmatt** [comment]
The Hackage revision is applied to 2.13.5.2. I see it on my end at least. 

I did release 2.13.6 without merging this! My bad. I will make another revision there.

**Comment by Vekhir** [comment]
> The Hackage revision is applied to 2.13.5.2. I see it on my end at least.

Now I can see it too. The version from few minutes ago (that I still have open) didn't have it. Just takes time for all servers I guess.

> I did release 2.13.6 without merging this! My bad. I will make another revision there.

Unfortunate! But thanks for merging it :+1:

**Pull request merged**
