### PR TITLE
Migrate Persistent wiki

### PR DESCRIPTION
**Pull request by psibi**
See https://github.com/yesodweb/persistent/issues/704 for the motivation behind it.

### CODE REVIEW

**Comment by paul-rouse** [comment]
I'm happy to look through this properly later if you want me to review it - can't give it enough time at the moment!

**Comment by paul-rouse** [comment]
I spotted one small error, a general point about the page titles, and some outdated links.  Once you have decided what to do about them, I should merge it!

* There is still a wiki-style link in `Persistent-entity-syntax.md` in the note below the first table ("the section below about timezone support")
* I would suggest making the original wiki page title a first-level header, eg in `Persistent-entity-syntax.md` add `#Persistent entity syntax` at the start, and similarly in the other pages.

Some of the links refer to outdated/moved material.  I just mention them now in case you want to repair them at the same time as this migration:

* There are two links to specific package versions in the `JSON instances` section of `Persistent-entity-syntax.md` - the version numbers could be deleted so as to always get the latest version.
* There's a link to the cookbook at the start of the `SQLite` section of `Database-Configuration.md`, and it ought to be changed to point to the new version `https://github.com/yesodweb/yesod-cookbook/blob/master/cookbook/Activate-foreign-key-checking-in-Sqlite.md`

**Comment by psibi** [comment]
Thanks for the detailed feedback. I have addressed all your comments in the latest push.

**Comment by paul-rouse** [comment]
I can't see what's wrong but that link you corrected ("the section below about timezone support") doesn't seem to display properly when I view [your branch](https://github.com/psibi/persistent/blob/persistent-docs/docs/Persistent-entity-syntax.md).  Maybe because the url fragment contains spaces (and doesn't actually correspond to a defined anchor)?

**Comment by psibi** [comment]
Sorry, my bad. It should be fixed right now.

**Comment by paul-rouse** [comment]
Fantastic!  I don't have any more comments, so go ahead and merge!

**Comment by psibi** [comment]
Thanks for the review!

**Pull request merged**
