### PR TITLE
Add support for SQL isolation levels

### PR DESCRIPTION
**Pull request by iand675**
This adds support for assorted SQL isolation levels to all of the standard SQL backends.

There is a slight breaking change for any dependent SQL backends in that the `connBegin` function now takes an optional isolation level argument. This is necessary because for MySQL the transaction isolation level must be specified before calling `begin`.  

- [x] Bumped the version number
- [x] Documented new APIs with [Haddock markup](https://www.haskell.org/haddock/doc/html/index.html)
- [x] Added [`@since` declarations](http://haskell-haddock.readthedocs.io/en/latest/markup.html#since) to the Haddock

After submitting your PR:

- [x] Update the Changelog.md file with a link to your PR
- [x] Check that CI passes (or if it fails, for reasons unrelated to your change, like CI timeouts)

### CODE REVIEW

**Comment by paul-rouse** [comment]
I don't feel very competent to approve this, especially for postgresql which I haven't used for years, but, that said, I've looked through the changes and they seem to be fine.  If nobody else steps in with comments, I'll go ahead in a few days.

**Comment by iand675** [comment]
Hi @paul-rouse, any chance you're ready to merge this yet?

**Comment by bitemyapp** [comment]
I'll take a look at this as I'm an active Persistent + PostgreSQL user.

**Comment by paul-rouse** [comment]
Thanks @bitemyapp !

**Comment by bitemyapp** [comment]
This is a very neat PR. Thank you @iand675, good seeing you around too :)

**Comment by iand675** [comment]
@bitemyapp Glad to you like it! Any notion on when it'll go up on hackage? Waiting to merge the corresponding yesod PRs til this is all the way shipped.

**Comment by bitemyapp** [comment]
@iand675 I'll take a sweep of open PRs this weekend, see what can make it in.

**Comment by CaptJakk** [comment]
Quickly wanted to check in and see if this can go to hackage/stackage. Otherwise would you recommend pinning this hash?

**Pull request merged**
